# yaml-language-server: $schema=https://raw.githubusercontent.com/inpyjamas/schemas/main/render.com.json
# https://render.com/docs/yaml-spec

services:
  - name: koding-ninja
    type: web
    env: static
    buildCommand: echo 1
    domains:
      - koding.ninja
    headers:
      - path: /*
        name: Cache-Control
        value: public, s-maxage=1, stale-while-revalidate=59
    routes:
      - type: redirect
        source: /
        destination: https://github.com/kodingdotninja
      - type: redirect
        source: /discord
        destination: https://discord.gg/aUnExRdAX6
    pullRequestPreviewsEnabled: true
    staticPublishPath: .
